### ISSUE TITLE
Incorrect output for ovrTackingState and StatusFlags

### ISSUE THREAD

**Issue by ericschv** [jselmani/cyclops#5]
`ovrTrackingState` and `StatusFlags` properties currently do not display a value greater than zero.

**Comment by ericschv** [comment]
@jselmani I think a better explanation is needed in order for others to understand the entire scope of this issue.

**Comment by jselmani** [comment]
`ovrTrackingState` and `StatusFlags` properties currently do not display a value greater than zero when being used in Unity.  We are yet to determine whether this is an initialization problem, or even an Oculus runtime issue.

`ovrTrackingState` is an object that allows for the tracking of the Rift HMD by the IR sensors and consequently provide us with data such as Angular Velocity, Linear Acceleration, and Yaw, Pitch, and Roll (very important values).

In order to have these values be printed to file, the `StatusFlags` property cannot be `0` and we must determine why that is the case currently.

#### Steps to Reproduce (STR)
1. Start Oculus Runtime (Oculus Home)
2. Put HMD on your head or where it can be noticed by the IR sensor.
3. Import DLL into Unity project.
4. Start scene.

When the scene is started in parallel to the console application currently, the data is written to console.  In this case however, nothing happens.

**Comment by jselmani** [comment]
No longer required.
